name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Lint
        run: npm run eslint
      - run: npm run build --if-present
      - run: npm test
      - name: E2E test
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          start: npm start
          wait-on: http://localhost:8080
